### ISSUE TITLE
Roadmap du PDF

### ISSUE THREAD

**Issue by Gue-sa** [Gue-sa/PDF-LFJM#1]
**Etape 1 :**

- [ ] S'accorder sur les éléments à traiter : 
    - [ ] Exemple
- [ ] Ajouter 1 à 3 exercices par niveau de difficulté.
- [ ] Rédiger les aides pour chaque exercice.
- [ ] Rédiger la FAQ sur la prépa.

**Etape 2: **

- [ ] Organiser les exercices par niveau de difficulté.
- [ ] Numéroter les exercices.
- [ ] Créer un chapitre "Aides", y stocker les aides et les lier aux exercices.
- [ ] Rédiger les remarques.
- [ ] Rédiger les éléments utiles.
- [ ] Rédiger les introductions aux nouvelles notions.
- [ ] Rédiger les anecdotes.
- [ ] Ajouter les liens pour aller plus loin.
